language: node_js
node_js:
  - "7"

install:
  - npm install

script:
  - npm run flow
  - npm run build

before_deploy:
  - sed -i "/\/build/d" .gitignore
  - bash deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
